INSERT INTO Estado (uf, nome, regiao, bandeira) VALUES
    ("AC", "Acre", "Norte", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/acre.png')),
    ("AL", "Alagoas", "Nordeste", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/alagoas.png')),
    ("AP", "Amapá", "Norte", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/amapa.png')),
    ("AM", "Amazonas", "Norte", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/amazonas.png')),
    ("BA", "Bahia", "Nordeste", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/bahia.png')),
    ("CE", "Ceará", "Nordeste", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/ceara.png')),
    ("DF", "Distrito Federal", "Centro-Oeste", null),
    ("ES", "Espírito Santo", "Sudeste", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/espirito-santo.png')),
    ("GO", "Goiás", "Centro-Oeste", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/goias.png')),
    ("MA", "Maranhão", "Nordeste", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/maranhao.png')),
    ("MT", "Mato Grosso", "Centro-Oeste", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/mato-grosso.png')),
    ("MS", "Mato Grosso do Sul", "Centro-Oeste", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/mato-grosso-do-sul.png')),
    ("MG", "Minas Gerais", "Sudeste", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/minas-gerais.png')),
    ("PA", "Pará", "Norte", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/para.png')),
    ("PB", "Paraíba", "Nordeste", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/paraiba.png')),
    ("PR", "Paraná", "Sul", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/parana.png')),
    ("PE", "Pernambuco", "Nordeste", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/pernambuco.png')),
    ("PI", "Piauí", "Nordeste", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/piaui.png')),
    ("RJ", "Rio de Janeiro", "Sudeste", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/rio-de-janeiro.png')),
    ("RN", "Rio Grande do Norte", "Nordeste", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/rio-grande-do-norte.png')),
    ("RS", "Rio Grande do Sul", "Sul", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/rio-grande-do-sul.png')),
    ("RO", "Rondônia", "Norte", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/rondonia.png')),
    ("RR", "Roraima", "Norte", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/roraima.png')),
    ("SC", "Santa Catarina", "Sul", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/santa-catarina.png')),
    ("SP", "São Paulo", "Sudeste", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/sao-paulo.png')),
    ("SE", "Sergipe", "Nordeste", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/sergipe.png')),
    ("TO", "Tocantins", "Norte", LOAD_FILE('/Users/jonny/Programming/UFRJ/Banco de Dados - 2016.1/BD-2016.1/images/tocantins.png'))
