
-- --------------------------------------------------------

--
-- Estrutura da tabela `Terceirizada`
--

CREATE TABLE `Terceirizada` (
  `id` int(11) NOT NULL,
  `tipo_servico` varchar(255) DEFAULT NULL,
  `nome` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Extraindo dados da tabela `Terceirizada`
--

INSERT INTO `Terceirizada` (`id`, `tipo_servico`, `nome`) VALUES
(1, 'Alimentação', 'Bluezoom'),
(2, 'Manutenção Geral', 'Oozz'),
(3, 'Manutenção Geral', 'Vinte'),
(4, 'Limpeza', 'Babbleopia'),
(5, 'Manutenção Geral', 'InnoZ'),
(6, 'Limpeza', 'Wikivu'),
(7, 'Manutenção Hidráulica', 'Skivee'),
(8, 'Segurança', 'Wordify'),
(9, 'Manutenção Elétrica', 'Skilith'),
(10, 'Alimentação', 'Babbleset'),
(11, 'Manutenção Elétrica', 'Dabfeed'),
(12, 'Manutenção Hidráulica', 'Trudeo'),
(13, 'Manutenção Hidráulica', 'Tagfeed'),
(14, 'Manutenção Hidráulica', 'Gabspot'),
(15, 'Alimentação', 'Bubbletube'),
(16, 'Segurança', 'Gabvine'),
(17, 'Manutenção Geral', 'Quamba'),
(18, 'Alimentação', 'Avavee'),
(19, 'Manutenção Elétrica', 'Fivespan'),
(20, 'Alimentação', 'Aimbu'),
(21, 'Segurança', 'Midel'),
(22, 'Manutenção Hidráulica', 'Izio'),
(23, 'Manutenção Elétrica', 'Kwinu'),
(24, 'Manutenção Elétrica', 'Dynabox'),
(25, 'Limpeza', 'Dabtype'),
(26, 'Manutenção Hidráulica', 'Photobug'),
(27, 'Limpeza', 'Wordpedia'),
(28, 'Alimentação', 'Skimia'),
(29, 'Segurança', 'Jaxspan'),
(30, 'Manutenção Elétrica', 'Edgeify'),
(31, 'Segurança', 'Dazzlesphere'),
(32, 'Limpeza', 'Camimbo'),
(33, 'Manutenção Hidráulica', 'Voolith'),
(34, 'Manutenção Geral', 'Fliptune'),
(35, 'Alimentação', 'Teklist'),
(36, 'Segurança', 'Divanoodle'),
(37, 'Alimentação', 'Tagtune'),
(38, 'Limpeza', 'Dazzlesphere'),
(39, 'Limpeza', 'Oloo'),
(40, 'Manutenção Hidráulica', 'Skipstorm'),
(41, 'Manutenção Elétrica', 'Eamia'),
(42, 'Manutenção Geral', 'Thoughtsphere'),
(43, 'Manutenção Geral', 'Jaxworks'),
(44, 'Alimentação', 'Kwideo'),
(45, 'Manutenção Hidráulica', 'Dynazzy'),
(46, 'Limpeza', 'Eimbee'),
(47, 'Segurança', 'Pixoboo'),
(48, 'Manutenção Elétrica', 'Tazz'),
(49, 'Segurança', 'Divavu'),
(50, 'Segurança', 'Dynazzy'),
(51, 'Segurança', 'Topdrive'),
(52, 'Alimentação', 'Meevee'),
(53, 'Limpeza', 'Mynte'),
(54, 'Manutenção Elétrica', 'Meeveo'),
(55, 'Segurança', 'Youspan'),
(56, 'Segurança', 'Jabbersphere'),
(57, 'Limpeza', 'Jabbersphere'),
(58, 'Manutenção Elétrica', 'Gevee'),
(59, 'Manutenção Elétrica', 'Jabbersphere'),
(60, 'Limpeza', 'Wordpedia'),
(61, 'Segurança', 'Oyoyo'),
(62, 'Segurança', 'Vidoo'),
(63, 'Manutenção Elétrica', 'Eabox'),
(64, 'Limpeza', 'Mynte'),
(65, 'Manutenção Hidráulica', 'Cogibox'),
(66, 'Limpeza', 'Npath'),
(67, 'Segurança', 'Edgeblab'),
(68, 'Manutenção Hidráulica', 'Yambee'),
(69, 'Manutenção Elétrica', 'Skyvu'),
(70, 'Manutenção Geral', 'Meembee'),
(71, 'Manutenção Hidráulica', 'Buzzbean'),
(72, 'Manutenção Geral', 'Zooxo'),
(73, 'Alimentação', 'Ooba'),
(74, 'Alimentação', 'Abatz'),
(75, 'Manutenção Geral', 'Quire'),
(76, 'Segurança', 'Wordpedia'),
(77, 'Limpeza', 'Ainyx'),
(78, 'Manutenção Geral', 'Thoughtmix'),
(79, 'Segurança', 'Skiba'),
(80, 'Manutenção Hidráulica', 'Zooxo'),
(81, 'Limpeza', 'Devify'),
(82, 'Segurança', 'Quire'),
(83, 'Alimentação', 'Dabvine'),
(84, 'Alimentação', 'Edgeblab'),
(85, 'Manutenção Elétrica', 'Eayo'),
(86, 'Manutenção Geral', 'Mudo'),
(87, 'Segurança', 'Flashspan'),
(88, 'Manutenção Elétrica', 'Mita'),
(89, 'Manutenção Elétrica', 'Topicstorm'),
(90, 'Segurança', 'Zoomcast'),
(91, 'Alimentação', 'Dabfeed'),
(92, 'Manutenção Hidráulica', 'Twitterbridge'),
(93, 'Manutenção Geral', 'Zoombox'),
(94, 'Manutenção Hidráulica', 'Skinder'),
(95, 'Limpeza', 'Edgeblab'),
(96, 'Limpeza', 'Skippad'),
(97, 'Manutenção Geral', 'Feedbug'),
(98, 'Manutenção Elétrica', 'Oyondu'),
(99, 'Limpeza', 'Geba'),
(100, 'Alimentação', 'Eare'),
(101, 'Segurança', 'Gabcube'),
(102, 'Segurança', 'Wordpedia'),
(103, 'Segurança', 'Gabcube'),
(104, 'Alimentação', 'Browsedrive'),
(105, 'Manutenção Elétrica', 'Agivu'),
(106, 'Manutenção Elétrica', 'Zoombeat'),
(107, 'Alimentação', 'Skaboo'),
(108, 'Alimentação', 'Roombo'),
(109, 'Limpeza', 'Chatterpoint'),
(110, 'Manutenção Hidráulica', 'Jetwire'),
(111, 'Manutenção Hidráulica', 'Tagpad'),
(112, 'Manutenção Geral', 'Linkbridge'),
(113, 'Manutenção Hidráulica', 'Ainyx'),
(114, 'Segurança', 'Zoomzone'),
(115, 'Manutenção Hidráulica', 'Jaxbean'),
(116, 'Manutenção Elétrica', 'Cogibox'),
(117, 'Manutenção Geral', 'Vinte'),
(118, 'Manutenção Geral', 'Browsezoom'),
(119, 'Manutenção Elétrica', 'Skyba'),
(120, 'Segurança', 'Feedfish'),
(121, 'Manutenção Geral', 'Realbuzz'),
(122, 'Limpeza', 'Mydo'),
(123, 'Manutenção Hidráulica', 'Bubblebox'),
(124, 'Manutenção Elétrica', 'JumpXS'),
(125, 'Manutenção Geral', 'Mydo'),
(126, 'Segurança', 'Feedspan'),
(127, 'Manutenção Hidráulica', 'Linkbridge'),
(128, 'Manutenção Elétrica', 'Tagtune'),
(129, 'Manutenção Hidráulica', 'Rhyloo'),
(130, 'Manutenção Hidráulica', 'Voolith'),
(131, 'Limpeza', 'Voonder'),
(132, 'Segurança', 'Photofeed'),
(133, 'Manutenção Geral', 'Centimia'),
(134, 'Segurança', 'Topiclounge'),
(135, 'Segurança', 'Skippad'),
(136, 'Manutenção Elétrica', 'Fanoodle'),
(137, 'Alimentação', 'Voonyx'),
(138, 'Manutenção Geral', 'Skipstorm'),
(139, 'Limpeza', 'Yamia'),
(140, 'Manutenção Elétrica', 'Zazio'),
(141, 'Segurança', 'Fadeo'),
(142, 'Segurança', 'Yodo'),
(143, 'Manutenção Hidráulica', 'Jaxbean'),
(144, 'Alimentação', 'Edgeblab'),
(145, 'Manutenção Elétrica', 'Myworks'),
(146, 'Limpeza', 'Yacero'),
(147, 'Manutenção Elétrica', 'Twitterbeat'),
(148, 'Manutenção Hidráulica', 'Twinder'),
(149, 'Limpeza', 'Youopia'),
(150, 'Manutenção Hidráulica', 'Ooba'),
(151, 'Segurança', 'Ntags'),
(152, 'Limpeza', 'Gigabox'),
(153, 'Segurança', 'Yambee'),
(154, 'Manutenção Geral', 'Blognation'),
(155, 'Manutenção Elétrica', 'Jetwire'),
(156, 'Manutenção Elétrica', 'Jabberbean'),
(157, 'Segurança', 'Rhycero'),
(158, 'Alimentação', 'Yozio'),
(159, 'Manutenção Hidráulica', 'Flashpoint'),
(160, 'Manutenção Geral', 'Gabtune'),
(161, 'Limpeza', 'Devbug'),
(162, 'Limpeza', 'Gigaclub'),
(163, 'Alimentação', 'Kimia'),
(164, 'Manutenção Geral', 'Feedmix'),
(165, 'Manutenção Elétrica', 'Katz'),
(166, 'Manutenção Hidráulica', 'Meetz'),
(167, 'Manutenção Hidráulica', 'Innojam'),
(168, 'Limpeza', 'Youspan'),
(169, 'Segurança', 'Fivechat'),
(170, 'Manutenção Hidráulica', 'Jazzy'),
(171, 'Limpeza', 'Meetz'),
(172, 'Manutenção Geral', 'Rhyloo'),
(173, 'Manutenção Elétrica', 'Katz'),
(174, 'Manutenção Geral', 'Zoonder'),
(175, 'Manutenção Hidráulica', 'Geba'),
(176, 'Segurança', 'Bubbletube'),
(177, 'Alimentação', 'Oba'),
(178, 'Segurança', 'Avamba'),
(179, 'Manutenção Hidráulica', 'Jetpulse'),
(180, 'Alimentação', 'Vinte'),
(181, 'Limpeza', 'Camimbo'),
(182, 'Manutenção Hidráulica', 'Brainsphere'),
(183, 'Manutenção Geral', 'Gabcube'),
(184, 'Manutenção Geral', 'Gabtune'),
(185, 'Manutenção Elétrica', 'Skyndu'),
(186, 'Manutenção Hidráulica', 'Edgepulse'),
(187, 'Alimentação', 'Jabbersphere'),
(188, 'Manutenção Geral', 'Tazz'),
(189, 'Segurança', 'Fivechat'),
(190, 'Limpeza', 'Zoovu'),
(191, 'Segurança', 'Wordify'),
(192, 'Alimentação', 'Demivee'),
(193, 'Segurança', 'Twitterlist'),
(194, 'Manutenção Hidráulica', 'Yodoo'),
(195, 'Limpeza', 'Flipopia'),
(196, 'Manutenção Hidráulica', 'Youtags'),
(197, 'Manutenção Hidráulica', 'Yabox'),
(198, 'Manutenção Geral', 'Twimbo'),
(199, 'Limpeza', 'Topiczoom'),
(200, 'Segurança', 'Oyope'),
(201, 'Manutenção Hidráulica', 'Trudoo'),
(202, 'Manutenção Hidráulica', 'Pixope'),
(203, 'Manutenção Geral', 'Wikizz'),
(204, 'Segurança', 'Rhyloo'),
(205, 'Limpeza', 'Zazio'),
(206, 'Limpeza', 'Devpulse'),
(207, 'Limpeza', 'Lazzy'),
(208, 'Segurança', 'Feedfish'),
(209, 'Limpeza', 'Devify'),
(210, 'Manutenção Elétrica', 'Edgepulse'),
(211, 'Segurança', 'Buzzshare'),
(212, 'Manutenção Geral', 'Realblab'),
(213, 'Manutenção Elétrica', 'Eire'),
(214, 'Segurança', 'Digitube'),
(215, 'Manutenção Elétrica', 'Jamia'),
(216, 'Segurança', 'Fliptune'),
(217, 'Manutenção Elétrica', 'Jabberstorm'),
(218, 'Manutenção Elétrica', 'Aivee'),
(219, 'Manutenção Elétrica', 'Shufflebeat'),
(220, 'Manutenção Geral', 'Innotype'),
(221, 'Alimentação', 'Aimbu'),
(222, 'Limpeza', 'Tagtune'),
(223, 'Manutenção Hidráulica', 'Rhybox'),
(224, 'Segurança', 'Livefish'),
(225, 'Manutenção Geral', 'Topiczoom'),
(226, 'Manutenção Geral', 'Kayveo'),
(227, 'Manutenção Geral', 'Eayo'),
(228, 'Manutenção Hidráulica', 'Meeveo'),
(229, 'Manutenção Hidráulica', 'Kayveo'),
(230, 'Limpeza', 'Linklinks'),
(231, 'Segurança', 'Avamm'),
(232, 'Segurança', 'Photolist'),
(233, 'Manutenção Hidráulica', 'Riffwire'),
(234, 'Limpeza', 'Voolia'),
(235, 'Manutenção Hidráulica', 'Pixoboo'),
(236, 'Limpeza', 'Shuffledrive'),
(237, 'Segurança', 'Gabspot'),
(238, 'Manutenção Geral', 'Realcube'),
(239, 'Manutenção Geral', 'Jaxnation'),
(240, 'Manutenção Elétrica', 'Divanoodle'),
(241, 'Manutenção Geral', 'Rhycero'),
(242, 'Segurança', 'Avaveo'),
(243, 'Limpeza', 'Flashpoint'),
(244, 'Manutenção Hidráulica', 'Oba'),
(245, 'Manutenção Geral', 'Snaptags'),
(246, 'Segurança', 'Skipfire'),
(247, 'Manutenção Geral', 'Roodel'),
(248, 'Segurança', 'Riffpath'),
(249, 'Manutenção Hidráulica', 'Chatterpoint'),
(250, 'Alimentação', 'Minyx'),
(251, 'Segurança', 'Kwilith'),
(252, 'Manutenção Elétrica', 'Flashpoint'),
(253, 'Alimentação', 'Yamia'),
(254, 'Manutenção Geral', 'Topicstorm'),
(255, 'Manutenção Hidráulica', 'Trupe'),
(256, 'Manutenção Hidráulica', 'Kazio'),
(257, 'Segurança', 'Meemm'),
(258, 'Segurança', 'Voonder'),
(259, 'Segurança', 'Nlounge'),
(260, 'Manutenção Elétrica', 'Shuffletag'),
(261, 'Segurança', 'Devshare'),
(262, 'Manutenção Geral', 'Jamia'),
(263, 'Manutenção Hidráulica', 'Avamm'),
(264, 'Manutenção Geral', 'Centidel'),
(265, 'Manutenção Elétrica', 'Kamba'),
(266, 'Manutenção Hidráulica', 'Yakitri'),
(267, 'Manutenção Geral', 'Shufflester'),
(268, 'Alimentação', 'Skinte'),
(269, 'Manutenção Elétrica', 'Skinder'),
(270, 'Limpeza', 'Gigabox'),
(271, 'Alimentação', 'Riffpath'),
(272, 'Alimentação', 'Yoveo'),
(273, 'Manutenção Elétrica', 'Bubblebox'),
(274, 'Manutenção Geral', 'Dabshots'),
(275, 'Manutenção Elétrica', 'Oba'),
(276, 'Manutenção Hidráulica', 'Yamia'),
(277, 'Manutenção Geral', 'Skyble'),
(278, 'Limpeza', 'Snaptags'),
(279, 'Manutenção Geral', 'Eamia'),
(280, 'Segurança', 'Skyvu'),
(281, 'Alimentação', 'Jabbersphere'),
(282, 'Segurança', 'Voonder'),
(283, 'Segurança', 'Mydeo'),
(284, 'Limpeza', 'Gigashots'),
(285, 'Segurança', 'Meejo'),
(286, 'Segurança', 'Twinte'),
(287, 'Limpeza', 'Meemm'),
(288, 'Alimentação', 'Buzzdog'),
(289, 'Manutenção Elétrica', 'Mudo'),
(290, 'Limpeza', 'Kwideo'),
(291, 'Alimentação', 'Oozz'),
(292, 'Manutenção Elétrica', 'Photobug'),
(293, 'Segurança', 'Topiclounge'),
(294, 'Segurança', 'Dabfeed'),
(295, 'Manutenção Hidráulica', 'Oyoloo'),
(296, 'Segurança', 'Fiveclub'),
(297, 'Limpeza', 'Npath'),
(298, 'Alimentação', 'Trupe'),
(299, 'Manutenção Geral', 'Skiptube'),
(300, 'Alimentação', 'Oloo'),
(301, 'Segurança', 'Twiyo'),
(302, 'Alimentação', 'Tazzy'),
(303, 'Alimentação', 'Thoughtblab'),
(304, 'Segurança', 'Roomm'),
(305, 'Manutenção Hidráulica', 'Brainsphere'),
(306, 'Manutenção Geral', 'Edgepulse'),
(307, 'Manutenção Hidráulica', 'Topdrive'),
(308, 'Manutenção Hidráulica', 'Zooveo'),
(309, 'Manutenção Elétrica', 'Thoughtsphere'),
(310, 'Manutenção Elétrica', 'Oyoloo'),
(311, 'Manutenção Hidráulica', 'Kwimbee'),
(312, 'Manutenção Geral', 'Avamm'),
(313, 'Manutenção Hidráulica', 'Trudeo'),
(314, 'Manutenção Hidráulica', 'Livepath'),
(315, 'Limpeza', 'Voonix'),
(316, 'Manutenção Elétrica', 'Zoovu'),
(317, 'Alimentação', 'Jaxspan'),
(318, 'Segurança', 'Janyx'),
(319, 'Limpeza', 'Livepath'),
(320, 'Manutenção Hidráulica', 'Blogtag'),
(321, 'Manutenção Elétrica', 'Snaptags'),
(322, 'Manutenção Geral', 'Aimbu'),
(323, 'Manutenção Elétrica', 'Wordware'),
(324, 'Segurança', 'Youfeed'),
(325, 'Manutenção Geral', 'Ooba'),
(326, 'Manutenção Elétrica', 'Midel'),
(327, 'Manutenção Geral', 'Meetz'),
(328, 'Limpeza', 'Wordpedia'),
(329, 'Segurança', 'Minyx'),
(330, 'Limpeza', 'Twinte'),
(331, 'Manutenção Geral', 'Kazio'),
(332, 'Manutenção Elétrica', 'Trudoo'),
(333, 'Alimentação', 'Wordtune'),
(334, 'Limpeza', 'Realblab'),
(335, 'Manutenção Hidráulica', 'Photofeed'),
(336, 'Segurança', 'Bluezoom'),
(337, 'Manutenção Hidráulica', 'Kwideo'),
(338, 'Manutenção Geral', 'Katz'),
(339, 'Alimentação', 'Skipstorm'),
(340, 'Manutenção Elétrica', 'Vipe'),
(341, 'Limpeza', 'Devify'),
(342, 'Limpeza', 'Ailane'),
(343, 'Alimentação', 'Realfire'),
(344, 'Limpeza', 'Trudoo'),
(345, 'Alimentação', 'Leenti'),
(346, 'Manutenção Hidráulica', 'Camido'),
(347, 'Segurança', 'Fadeo'),
(348, 'Limpeza', 'Avaveo'),
(349, 'Segurança', 'Skimia'),
(350, 'Manutenção Elétrica', 'Browsecat'),
(351, 'Manutenção Hidráulica', 'Skinix'),
(352, 'Manutenção Hidráulica', 'Brightbean'),
(353, 'Manutenção Geral', 'Izio'),
(354, 'Manutenção Geral', 'Meetz'),
(355, 'Manutenção Geral', 'Gigazoom'),
(356, 'Manutenção Elétrica', 'Leenti'),
(357, 'Limpeza', 'Cogidoo'),
(358, 'Manutenção Elétrica', 'Oyonder'),
(359, 'Manutenção Geral', 'Kaymbo'),
(360, 'Manutenção Geral', 'Flashdog'),
(361, 'Manutenção Elétrica', 'Tagpad'),
(362, 'Segurança', 'Camido'),
(363, 'Manutenção Geral', 'Livepath'),
(364, 'Manutenção Elétrica', 'Oba'),
(365, 'Manutenção Geral', 'Edgewire'),
(366, 'Alimentação', 'Gabcube'),
(367, 'Segurança', 'Wikizz'),
(368, 'Manutenção Elétrica', 'Tekfly'),
(369, 'Manutenção Elétrica', 'Trupe'),
(370, 'Manutenção Hidráulica', 'Plambee'),
(371, 'Manutenção Geral', 'Skivee'),
(372, 'Manutenção Hidráulica', 'Roombo'),
(373, 'Manutenção Elétrica', 'Rhybox'),
(374, 'Manutenção Elétrica', 'Skynoodle'),
(375, 'Manutenção Hidráulica', 'Katz'),
(376, 'Manutenção Elétrica', 'Topdrive'),
(377, 'Alimentação', 'Mynte'),
(378, 'Manutenção Geral', 'Aimbo'),
(379, 'Limpeza', 'Jayo'),
(380, 'Manutenção Hidráulica', 'Meejo'),
(381, 'Segurança', 'Divanoodle'),
(382, 'Manutenção Geral', 'Trudoo'),
(383, 'Segurança', 'Jabbersphere'),
(384, 'Manutenção Elétrica', 'Babblestorm'),
(385, 'Manutenção Elétrica', 'Centizu'),
(386, 'Manutenção Elétrica', 'Kazu'),
(387, 'Manutenção Geral', 'Skivee'),
(388, 'Limpeza', 'Wordware'),
(389, 'Segurança', 'Yacero'),
(390, 'Manutenção Geral', 'Blognation'),
(391, 'Manutenção Elétrica', 'Zoomcast'),
(392, 'Manutenção Elétrica', 'Fivebridge'),
(393, 'Segurança', 'Wikibox'),
(394, 'Manutenção Hidráulica', 'Tagfeed'),
(395, 'Limpeza', 'Topiclounge'),
(396, 'Alimentação', 'Cogilith'),
(397, 'Segurança', 'Rhyloo'),
(398, 'Manutenção Geral', 'Zoombeat'),
(399, 'Alimentação', 'Skyvu'),
(400, 'Alimentação', 'Devshare'),
(401, 'Manutenção Geral', 'Photolist'),
(402, 'Segurança', 'Fatz'),
(403, 'Segurança', 'Geba'),
(404, 'Segurança', 'Shuffletag'),
(405, 'Segurança', 'Skaboo'),
(406, 'Limpeza', 'Voonyx'),
(407, 'Manutenção Hidráulica', 'Kanoodle'),
(408, 'Limpeza', 'Voomm'),
(409, 'Manutenção Hidráulica', 'Ntags'),
(410, 'Segurança', 'Jayo'),
(411, 'Manutenção Hidráulica', 'Aimbu'),
(412, 'Alimentação', 'Dabjam'),
(413, 'Manutenção Hidráulica', 'Devpulse'),
(414, 'Segurança', 'Jabberstorm'),
(415, 'Limpeza', 'Tazz'),
(416, 'Manutenção Elétrica', 'Linkbridge'),
(417, 'Alimentação', 'InnoZ'),
(418, 'Segurança', 'Shuffletag'),
(419, 'Limpeza', 'Eare'),
(420, 'Manutenção Elétrica', 'Flashspan'),
(421, 'Manutenção Hidráulica', 'Quatz'),
(422, 'Segurança', 'Linkbuzz'),
(423, 'Manutenção Geral', 'Youtags'),
(424, 'Manutenção Geral', 'Skaboo'),
(425, 'Segurança', 'Lazzy'),
(426, 'Segurança', 'Skyble'),
(427, 'Segurança', 'Jabbersphere'),
(428, 'Segurança', 'Gabtune'),
(429, 'Alimentação', 'Katz'),
(430, 'Manutenção Elétrica', 'Skivee'),
(431, 'Manutenção Elétrica', 'Jabberstorm'),
(432, 'Manutenção Hidráulica', 'Avamm'),
(433, 'Alimentação', 'Thoughtbeat'),
(434, 'Manutenção Hidráulica', 'Dynabox'),
(435, 'Segurança', 'Riffwire'),
(436, 'Alimentação', 'Realbuzz'),
(437, 'Alimentação', 'Jamia'),
(438, 'Manutenção Elétrica', 'Demizz'),
(439, 'Manutenção Hidráulica', 'Eayo'),
(440, 'Segurança', 'Edgepulse'),
(441, 'Alimentação', 'Jabbercube'),
(442, 'Segurança', 'Voomm'),
(443, 'Manutenção Hidráulica', 'Yombu'),
(444, 'Limpeza', 'Kaymbo'),
(445, 'Manutenção Elétrica', 'Devify'),
(446, 'Manutenção Geral', 'Topicstorm'),
(447, 'Alimentação', 'Youtags'),
(448, 'Manutenção Geral', 'Aivee'),
(449, 'Manutenção Hidráulica', 'Browsebug'),
(450, 'Alimentação', 'Lazz'),
(451, 'Limpeza', 'Livepath'),
(452, 'Manutenção Geral', 'Photobug'),
(453, 'Manutenção Hidráulica', 'Teklist'),
(454, 'Manutenção Hidráulica', 'Avavee'),
(455, 'Manutenção Elétrica', 'Gabspot'),
(456, 'Alimentação', 'Tagfeed'),
(457, 'Manutenção Hidráulica', 'Quatz'),
(458, 'Alimentação', 'Kwinu'),
(459, 'Limpeza', 'Centidel'),
(460, 'Alimentação', 'Fadeo'),
(461, 'Manutenção Geral', 'Jaxbean'),
(462, 'Limpeza', 'Zoomlounge'),
(463, 'Segurança', 'Topicblab'),
(464, 'Manutenção Elétrica', 'Tekfly'),
(465, 'Manutenção Elétrica', 'Thoughtworks'),
(466, 'Manutenção Hidráulica', 'Feedmix'),
(467, 'Manutenção Elétrica', 'Oodoo'),
(468, 'Alimentação', 'Meezzy'),
(469, 'Alimentação', 'Twiyo'),
(470, 'Manutenção Elétrica', 'Gevee'),
(471, 'Manutenção Elétrica', 'JumpXS'),
(472, 'Manutenção Geral', 'Trudeo'),
(473, 'Segurança', 'Riffwire'),
(474, 'Manutenção Hidráulica', 'Jetpulse'),
(475, 'Segurança', 'Bluezoom'),
(476, 'Manutenção Hidráulica', 'Oba'),
(477, 'Manutenção Elétrica', 'Midel'),
(478, 'Manutenção Geral', 'Trudoo'),
(479, 'Manutenção Geral', 'InnoZ'),
(480, 'Alimentação', 'Aibox'),
(481, 'Manutenção Geral', 'Skidoo'),
(482, 'Segurança', 'Trunyx'),
(483, 'Manutenção Hidráulica', 'Chatterbridge'),
(484, 'Alimentação', 'Mita'),
(485, 'Manutenção Hidráulica', 'Zoombox'),
(486, 'Alimentação', 'Jabbertype'),
(487, 'Manutenção Geral', 'Wordware'),
(488, 'Segurança', 'Cogidoo'),
(489, 'Manutenção Elétrica', 'Brightbean'),
(490, 'Limpeza', 'Quinu'),
(491, 'Segurança', 'Quinu'),
(492, 'Manutenção Hidráulica', 'Kwilith'),
(493, 'Segurança', 'Twitterlist'),
(494, 'Manutenção Hidráulica', 'Edgeify'),
(495, 'Alimentação', 'Mudo'),
(496, 'Segurança', 'Pixope'),
(497, 'Segurança', 'Chatterbridge'),
(498, 'Manutenção Hidráulica', 'Voomm'),
(499, 'Segurança', 'Demizz'),
(500, 'Alimentação', 'Abata'),
(501, 'Manutenção Geral', 'Aimbo'),
(502, 'Manutenção Elétrica', 'Quamba'),
(503, 'Manutenção Geral', 'Twitterlist'),
(504, 'Limpeza', 'Tazz'),
(505, 'Alimentação', 'Flipopia'),
(506, 'Manutenção Elétrica', 'Gigazoom'),
(507, 'Segurança', 'Zoomzone'),
(508, 'Manutenção Elétrica', 'Agimba'),
(509, 'Manutenção Geral', 'Leexo'),
(510, 'Limpeza', 'Jabbersphere'),
(511, 'Segurança', 'Jazzy'),
(512, 'Limpeza', 'Twitterwire'),
(513, 'Manutenção Hidráulica', 'Yata'),
(514, 'Limpeza', 'Skiba'),
(515, 'Manutenção Geral', 'Eamia'),
(516, 'Alimentação', 'Topdrive'),
(517, 'Manutenção Elétrica', 'Snaptags'),
(518, 'Limpeza', 'Twimm'),
(519, 'Manutenção Elétrica', 'Feedspan'),
(520, 'Manutenção Elétrica', 'Trilith'),
(521, 'Alimentação', 'Topicshots'),
(522, 'Alimentação', 'Skyba'),
(523, 'Manutenção Elétrica', 'Innojam'),
(524, 'Manutenção Elétrica', 'Babbleblab'),
(525, 'Manutenção Geral', 'Jatri'),
(526, 'Manutenção Elétrica', 'Rhynyx'),
(527, 'Segurança', 'Bluejam'),
(528, 'Alimentação', 'Voomm'),
(529, 'Manutenção Elétrica', 'Gabtype'),
(530, 'Manutenção Hidráulica', 'Topicblab'),
(531, 'Segurança', 'Riffwire'),
(532, 'Alimentação', 'Snaptags'),
(533, 'Manutenção Elétrica', 'Tanoodle'),
(534, 'Alimentação', 'Agivu'),
(535, 'Manutenção Hidráulica', 'Mydeo'),
(536, 'Alimentação', 'Jaxspan'),
(537, 'Manutenção Hidráulica', 'Fivebridge'),
(538, 'Segurança', 'Gigazoom'),
(539, 'Segurança', 'Photolist'),
(540, 'Manutenção Geral', 'Yambee'),
(541, 'Manutenção Elétrica', 'Shufflebeat'),
(542, 'Manutenção Hidráulica', 'Zooveo'),
(543, 'Alimentação', 'Yodoo'),
(544, 'Manutenção Hidráulica', 'Kayveo'),
(545, 'Alimentação', 'Devify'),
(546, 'Manutenção Elétrica', 'Riffpath'),
(547, 'Manutenção Geral', 'Dynava'),
(548, 'Alimentação', 'Flipbug'),
(549, 'Manutenção Geral', 'Realblab'),
(550, 'Manutenção Geral', 'Thoughtstorm'),
(551, 'Limpeza', 'Wordify'),
(552, 'Manutenção Elétrica', 'Youopia'),
(553, 'Manutenção Hidráulica', 'Oozz'),
(554, 'Manutenção Hidráulica', 'Devshare'),
(555, 'Manutenção Hidráulica', 'Skinte'),
(556, 'Manutenção Elétrica', 'Photobean'),
(557, 'Alimentação', 'Skiptube'),
(558, 'Manutenção Geral', 'Realbuzz'),
(559, 'Alimentação', 'Vitz'),
(560, 'Manutenção Geral', 'Fatz'),
(561, 'Segurança', 'Viva'),
(562, 'Manutenção Hidráulica', 'Shuffletag'),
(563, 'Alimentação', 'Thoughtblab'),
(564, 'Segurança', 'Linktype'),
(565, 'Limpeza', 'Thoughtbeat'),
(566, 'Alimentação', 'Dabtype'),
(567, 'Segurança', 'Mycat'),
(568, 'Manutenção Geral', 'Vinder'),
(569, 'Manutenção Hidráulica', 'Fatz'),
(570, 'Manutenção Elétrica', 'Kare'),
(571, 'Manutenção Elétrica', 'Blogtags'),
(572, 'Segurança', 'Dynabox'),
(573, 'Limpeza', 'Kwilith'),
(574, 'Segurança', 'Trupe'),
(575, 'Alimentação', 'Eadel'),
(576, 'Limpeza', 'Yakidoo'),
(577, 'Alimentação', 'Tazz'),
(578, 'Manutenção Elétrica', 'Kamba'),
(579, 'Manutenção Geral', 'Brightdog'),
(580, 'Segurança', 'Dynava'),
(581, 'Manutenção Geral', 'Livefish'),
(582, 'Manutenção Elétrica', 'Flipbug'),
(583, 'Segurança', 'Browsecat'),
(584, 'Limpeza', 'Jabbersphere'),
(585, 'Manutenção Geral', 'Oyoba'),
(586, 'Manutenção Elétrica', 'Quinu'),
(587, 'Alimentação', 'Trunyx'),
(588, 'Segurança', 'Voonte'),
(589, 'Alimentação', 'Rhycero'),
(590, 'Segurança', 'Ntag'),
(591, 'Manutenção Geral', 'Jetwire'),
(592, 'Manutenção Hidráulica', 'Gigabox'),
(593, 'Manutenção Elétrica', 'Skynoodle'),
(594, 'Alimentação', 'Gigashots'),
(595, 'Manutenção Geral', 'Centizu'),
(596, 'Alimentação', 'Kazu'),
(597, 'Alimentação', 'Oyope'),
(598, 'Segurança', 'Roomm'),
(599, 'Limpeza', 'Wikizz'),
(600, 'Limpeza', 'Twitterbeat'),
(601, 'Manutenção Elétrica', 'Flipstorm'),
(602, 'Segurança', 'Skajo'),
(603, 'Manutenção Elétrica', 'Skipfire'),
(604, 'Limpeza', 'Livepath'),
(605, 'Limpeza', 'Devpoint'),
(606, 'Manutenção Elétrica', 'Yodel'),
(607, 'Alimentação', 'Twimm'),
(608, 'Limpeza', 'Rooxo'),
(609, 'Manutenção Geral', 'Kwinu'),
(610, 'Segurança', 'Rhyzio'),
(611, 'Manutenção Geral', 'Zooveo'),
(612, 'Manutenção Hidráulica', 'Topicshots'),
(613, 'Segurança', 'Kaymbo'),
(614, 'Alimentação', 'Oba'),
(615, 'Alimentação', 'Kimia'),
(616, 'Manutenção Hidráulica', 'Einti'),
(617, 'Limpeza', 'Chatterpoint'),
(618, 'Manutenção Hidráulica', 'Myworks'),
(619, 'Manutenção Geral', 'Kwimbee'),
(620, 'Limpeza', 'Flashset'),
(621, 'Manutenção Hidráulica', 'Thoughtmix'),
(622, 'Manutenção Hidráulica', 'Gabvine'),
(623, 'Alimentação', 'Yata'),
(624, 'Limpeza', 'Linklinks'),
(625, 'Limpeza', 'Ozu'),
(626, 'Limpeza', 'Wikido'),
(627, 'Segurança', 'Aimbu'),
(628, 'Manutenção Hidráulica', 'Twinte'),
(629, 'Manutenção Geral', 'Zoomcast'),
(630, 'Alimentação', 'Twitterworks'),
(631, 'Manutenção Elétrica', 'Mybuzz'),
(632, 'Limpeza', 'Skibox'),
(633, 'Manutenção Elétrica', 'Yamia'),
(634, 'Alimentação', 'Buzzbean'),
(635, 'Manutenção Elétrica', 'Eire'),
(636, 'Alimentação', 'Yacero'),
(637, 'Limpeza', 'Wikivu'),
(638, 'Segurança', 'Topiclounge'),
(639, 'Manutenção Elétrica', 'Skyndu'),
(640, 'Limpeza', 'Dazzlesphere'),
(641, 'Limpeza', 'Trilith'),
(642, 'Limpeza', 'Gigashots'),
(643, 'Alimentação', 'Buzzbean'),
(644, 'Manutenção Elétrica', 'Shuffledrive'),
(645, 'Segurança', 'Yata'),
(646, 'Limpeza', 'Flipopia'),
(647, 'Manutenção Elétrica', 'Rhyloo'),
(648, 'Manutenção Hidráulica', 'Gabcube'),
(649, 'Limpeza', 'Quinu'),
(650, 'Alimentação', 'Oodoo'),
(651, 'Manutenção Elétrica', 'Gevee'),
(652, 'Segurança', 'Youfeed'),
(653, 'Alimentação', 'Miboo'),
(654, 'Limpeza', 'Flashdog'),
(655, 'Alimentação', 'Dabjam'),
(656, 'Limpeza', 'Mynte'),
(657, 'Limpeza', 'Jabbersphere'),
(658, 'Manutenção Elétrica', 'Skiba'),
(659, 'Manutenção Elétrica', 'Digitube'),
(660, 'Alimentação', 'Yakidoo'),
(661, 'Manutenção Geral', 'Fatz'),
(662, 'Alimentação', 'Jaxworks'),
(663, 'Limpeza', 'Edgeblab'),
(664, 'Manutenção Elétrica', 'Ozu'),
(665, 'Segurança', 'Meembee'),
(666, 'Segurança', 'Talane'),
(667, 'Limpeza', 'Fivespan'),
(668, 'Manutenção Geral', 'Voolia'),
(669, 'Limpeza', 'Meejo'),
(670, 'Segurança', 'Edgewire'),
(671, 'Manutenção Elétrica', 'Realmix'),
(672, 'Alimentação', 'Vinder'),
(673, 'Manutenção Geral', 'Photolist'),
(674, 'Manutenção Geral', 'Skipfire'),
(675, 'Alimentação', 'Livetube'),
(676, 'Manutenção Elétrica', 'Thoughtstorm'),
(677, 'Segurança', 'Realcube'),
(678, 'Alimentação', 'Thoughtstorm'),
(679, 'Manutenção Hidráulica', 'Twinte'),
(680, 'Manutenção Elétrica', 'Wikizz'),
(681, 'Manutenção Geral', 'Rooxo'),
(682, 'Alimentação', 'Vinte'),
(683, 'Segurança', 'Voomm'),
(684, 'Alimentação', 'Photobug'),
(685, 'Manutenção Geral', 'Quinu'),
(686, 'Segurança', 'Jetwire'),
(687, 'Limpeza', 'Thoughtblab'),
(688, 'Alimentação', 'Meevee'),
(689, 'Manutenção Geral', 'Skyba'),
(690, 'Limpeza', 'Eabox'),
(691, 'Limpeza', 'Zoomlounge'),
(692, 'Limpeza', 'Feedbug'),
(693, 'Manutenção Geral', 'Eazzy'),
(694, 'Segurança', 'Pixope'),
(695, 'Manutenção Hidráulica', 'Pixoboo'),
(696, 'Alimentação', 'Voomm'),
(697, 'Manutenção Geral', 'Twitterwire'),
(698, 'Limpeza', 'Photobug'),
(699, 'Manutenção Elétrica', 'Kanoodle'),
(700, 'Alimentação', 'Jaloo'),
(701, 'Manutenção Geral', 'Dabfeed'),
(702, 'Segurança', 'Twitterbridge'),
(703, 'Alimentação', 'Yakijo'),
(704, 'Manutenção Hidráulica', 'Quamba'),
(705, 'Alimentação', 'Jetpulse'),
(706, 'Manutenção Elétrica', 'Wordpedia'),
(707, 'Manutenção Elétrica', 'Topicware'),
(708, 'Manutenção Hidráulica', 'Babbleset'),
(709, 'Manutenção Elétrica', 'Realbuzz'),
(710, 'Segurança', 'Vimbo'),
(711, 'Segurança', 'Leenti'),
(712, 'Alimentação', 'Jabbercube'),
(713, 'Limpeza', 'Plambee'),
(714, 'Segurança', 'Wikizz'),
(715, 'Manutenção Geral', 'Livepath'),
(716, 'Manutenção Elétrica', 'Topiclounge'),
(717, 'Limpeza', 'Yozio'),
(718, 'Manutenção Geral', 'Fatz'),
(719, 'Manutenção Hidráulica', 'Livetube'),
(720, 'Segurança', 'Riffpath'),
(721, 'Alimentação', 'Zoomcast'),
(722, 'Segurança', 'Flashpoint'),
(723, 'Manutenção Geral', 'Youopia'),
(724, 'Segurança', 'Babbleblab'),
(725, 'Alimentação', 'Agivu'),
(726, 'Segurança', 'Voonte'),
(727, 'Manutenção Hidráulica', 'Youtags'),
(728, 'Segurança', 'Zoonoodle'),
(729, 'Manutenção Elétrica', 'Flipstorm'),
(730, 'Manutenção Hidráulica', 'Camido'),
(731, 'Manutenção Geral', 'Zooveo'),
(732, 'Alimentação', 'Rhynoodle'),
(733, 'Manutenção Geral', 'Eayo'),
(734, 'Alimentação', 'Voomm'),
(735, 'Manutenção Elétrica', 'Bluezoom'),
(736, 'Limpeza', 'Quatz'),
(737, 'Manutenção Geral', 'Jamia'),
(738, 'Limpeza', 'Yacero'),
(739, 'Manutenção Geral', 'Thoughtblab'),
(740, 'Manutenção Geral', 'Roodel'),
(741, 'Segurança', 'Plambee'),
(742, 'Limpeza', 'Vidoo'),
(743, 'Segurança', 'Oodoo'),
(744, 'Segurança', 'Meevee'),
(745, 'Manutenção Geral', 'Skivee'),
(746, 'Alimentação', 'Devshare'),
(747, 'Manutenção Geral', 'Twitterlist'),
(748, 'Alimentação', 'Browsecat'),
(749, 'Manutenção Hidráulica', 'Dabshots'),
(750, 'Limpeza', 'Pixoboo'),
(751, 'Manutenção Geral', 'Bubbletube'),
(752, 'Manutenção Elétrica', 'Kwimbee'),
(753, 'Alimentação', 'Vimbo'),
(754, 'Segurança', 'Oyope'),
(755, 'Manutenção Elétrica', 'Jaxspan'),
(756, 'Alimentação', 'Quatz'),
(757, 'Manutenção Elétrica', 'Realbuzz'),
(758, 'Alimentação', 'Rhycero'),
(759, 'Alimentação', 'Yamia'),
(760, 'Manutenção Elétrica', 'Trudeo'),
(761, 'Manutenção Hidráulica', 'Wikido'),
(762, 'Manutenção Geral', 'Realfire'),
(763, 'Manutenção Geral', 'Kwideo'),
(764, 'Alimentação', 'Skidoo'),
(765, 'Manutenção Elétrica', 'Edgeify'),
(766, 'Limpeza', 'Meembee'),
(767, 'Manutenção Hidráulica', 'Skipfire'),
(768, 'Alimentação', 'Yamia'),
(769, 'Alimentação', 'Rhybox'),
(770, 'Manutenção Hidráulica', 'Trilith'),
(771, 'Manutenção Hidráulica', 'Skinix'),
(772, 'Alimentação', 'Oodoo'),
(773, 'Manutenção Hidráulica', 'Rhynoodle'),
(774, 'Manutenção Geral', 'DabZ'),
(775, 'Limpeza', 'Eidel'),
(776, 'Alimentação', 'Plajo'),
(777, 'Alimentação', 'Photobug'),
(778, 'Manutenção Hidráulica', 'Tagfeed'),
(779, 'Manutenção Hidráulica', 'Kamba'),
(780, 'Manutenção Geral', 'Mydo'),
(781, 'Manutenção Hidráulica', 'Blogpad'),
(782, 'Manutenção Elétrica', 'Yadel'),
(783, 'Segurança', 'Aibox'),
(784, 'Manutenção Elétrica', 'Topdrive'),
(785, 'Manutenção Hidráulica', 'Yakidoo'),
(786, 'Manutenção Elétrica', 'Kimia'),
(787, 'Segurança', 'Tekfly'),
(788, 'Segurança', 'Wikido'),
(789, 'Manutenção Geral', 'Yotz'),
(790, 'Manutenção Geral', 'Blogtags'),
(791, 'Limpeza', 'Brightbean'),
(792, 'Manutenção Hidráulica', 'Topicware'),
(793, 'Segurança', 'Twimm'),
(794, 'Manutenção Hidráulica', 'Eimbee'),
(795, 'Manutenção Elétrica', 'Topiczoom'),
(796, 'Manutenção Hidráulica', 'Thoughtstorm'),
(797, 'Segurança', 'Meetz'),
(798, 'Manutenção Elétrica', 'Linktype'),
(799, 'Limpeza', 'Topicshots'),
(800, 'Segurança', 'Aimbo'),
(801, 'Limpeza', 'Plajo'),
(802, 'Limpeza', 'Rhycero'),
(803, 'Alimentação', 'Tagcat'),
(804, 'Manutenção Geral', 'Meemm'),
(805, 'Alimentação', 'Feedmix'),
(806, 'Limpeza', 'Gigaclub'),
(807, 'Manutenção Elétrica', 'Innojam'),
(808, 'Manutenção Elétrica', 'Tagtune'),
(809, 'Segurança', 'Kaymbo'),
(810, 'Segurança', 'Linkbuzz'),
(811, 'Manutenção Hidráulica', 'Buzzshare'),
(812, 'Segurança', 'Bubblebox'),
(813, 'Alimentação', 'Yotz'),
(814, 'Alimentação', 'Nlounge'),
(815, 'Manutenção Hidráulica', 'Wikido'),
(816, 'Alimentação', 'Divape'),
(817, 'Manutenção Elétrica', 'Podcat'),
(818, 'Manutenção Hidráulica', 'Topiczoom'),
(819, 'Limpeza', 'Nlounge'),
(820, 'Manutenção Elétrica', 'Kwimbee'),
(821, 'Manutenção Hidráulica', 'Mynte'),
(822, 'Limpeza', 'Yadel'),
(823, 'Manutenção Hidráulica', 'Eare'),
(824, 'Manutenção Elétrica', 'Podcat'),
(825, 'Manutenção Hidráulica', 'Dabjam'),
(826, 'Manutenção Elétrica', 'Jayo'),
(827, 'Manutenção Geral', 'Zoomlounge'),
(828, 'Limpeza', 'Tekfly'),
(829, 'Manutenção Elétrica', 'Yozio'),
(830, 'Manutenção Elétrica', 'Kwilith'),
(831, 'Manutenção Hidráulica', 'Youfeed'),
(832, 'Limpeza', 'Riffwire'),
(833, 'Alimentação', 'Katz'),
(834, 'Alimentação', 'Blogpad'),
(835, 'Limpeza', 'Tagpad'),
(836, 'Manutenção Elétrica', 'Trupe'),
(837, 'Segurança', 'Skidoo'),
(838, 'Manutenção Elétrica', 'Twimbo'),
(839, 'Manutenção Geral', 'Oyondu'),
(840, 'Manutenção Geral', 'Fivebridge'),
(841, 'Manutenção Elétrica', 'Skivee'),
(842, 'Manutenção Hidráulica', 'Skidoo'),
(843, 'Limpeza', 'Devbug'),
(844, 'Manutenção Elétrica', 'Eadel'),
(845, 'Segurança', 'Feedfish'),
(846, 'Manutenção Hidráulica', 'Dabshots'),
(847, 'Limpeza', 'Flashset'),
(848, 'Manutenção Geral', 'Kwideo'),
(849, 'Segurança', 'Buzzster'),
(850, 'Alimentação', 'Aivee'),
(851, 'Manutenção Hidráulica', 'Thoughtbeat'),
(852, 'Manutenção Hidráulica', 'Jayo'),
(853, 'Manutenção Geral', 'Eabox'),
(854, 'Alimentação', 'Roombo'),
(855, 'Manutenção Hidráulica', 'Riffpath'),
(856, 'Manutenção Geral', 'Photobug'),
(857, 'Alimentação', 'Meevee'),
(858, 'Limpeza', 'Feedbug'),
(859, 'Manutenção Geral', 'Rhynyx'),
(860, 'Manutenção Elétrica', 'Thoughtbeat'),
(861, 'Segurança', 'Devcast'),
(862, 'Manutenção Geral', 'Wikivu'),
(863, 'Alimentação', 'Cogilith'),
(864, 'Limpeza', 'Gabtype'),
(865, 'Manutenção Hidráulica', 'Gigashots'),
(866, 'Manutenção Geral', 'Thoughtblab'),
(867, 'Segurança', 'Centidel'),
(868, 'Alimentação', 'Podcat'),
(869, 'Manutenção Geral', 'Edgeify'),
(870, 'Manutenção Hidráulica', 'Fatz'),
(871, 'Manutenção Hidráulica', 'Zoovu'),
(872, 'Manutenção Elétrica', 'Photobug'),
(873, 'Manutenção Elétrica', 'Yodo'),
(874, 'Manutenção Hidráulica', 'Skibox'),
(875, 'Segurança', 'Flipstorm'),
(876, 'Alimentação', 'Innojam'),
(877, 'Manutenção Geral', 'Rhynyx'),
(878, 'Manutenção Elétrica', 'Centidel'),
(879, 'Limpeza', 'Babbleopia'),
(880, 'Manutenção Geral', 'Abatz'),
(881, 'Limpeza', 'Lazz'),
(882, 'Manutenção Geral', 'Edgetag'),
(883, 'Manutenção Hidráulica', 'Realbuzz'),
(884, 'Manutenção Hidráulica', 'Meeveo'),
(885, 'Alimentação', 'Zoomlounge'),
(886, 'Segurança', 'Yambee'),
(887, 'Alimentação', 'Oozz'),
(888, 'Manutenção Elétrica', 'Jayo'),
(889, 'Manutenção Hidráulica', 'Skiptube'),
(890, 'Manutenção Geral', 'Thoughtbeat'),
(891, 'Manutenção Hidráulica', 'Voolith'),
(892, 'Manutenção Elétrica', 'Npath'),
(893, 'Manutenção Hidráulica', 'Kaymbo'),
(894, 'Segurança', 'Gigashots'),
(895, 'Manutenção Elétrica', 'Jaloo'),
(896, 'Alimentação', 'Geba'),
(897, 'Manutenção Elétrica', 'Avamm'),
(898, 'Manutenção Hidráulica', 'Yozio'),
(899, 'Alimentação', 'Photobug'),
(900, 'Manutenção Geral', 'Skalith'),
(901, 'Limpeza', 'Vipe'),
(902, 'Manutenção Elétrica', 'Pixoboo'),
(903, 'Manutenção Geral', 'Rhyloo'),
(904, 'Limpeza', 'Ntag'),
(905, 'Manutenção Hidráulica', 'Edgeify'),
(906, 'Manutenção Hidráulica', 'Topicshots'),
(907, 'Alimentação', 'Yabox'),
(908, 'Alimentação', 'Innotype'),
(909, 'Manutenção Elétrica', 'Yamia'),
(910, 'Segurança', 'Edgeblab'),
(911, 'Manutenção Geral', 'Zava'),
(912, 'Segurança', 'Photolist'),
(913, 'Alimentação', 'Mynte'),
(914, 'Manutenção Elétrica', 'Kamba'),
(915, 'Manutenção Geral', 'Eidel'),
(916, 'Manutenção Elétrica', 'Realblab'),
(917, 'Manutenção Hidráulica', 'Mydeo'),
(918, 'Alimentação', 'Voonix'),
(919, 'Limpeza', 'Livetube'),
(920, 'Alimentação', 'Yoveo'),
(921, 'Manutenção Elétrica', 'Dabtype'),
(922, 'Manutenção Elétrica', 'Vidoo'),
(923, 'Segurança', 'Digitube'),
(924, 'Alimentação', 'Twitterwire'),
(925, 'Manutenção Geral', 'Meembee'),
(926, 'Segurança', 'Eidel'),
(927, 'Alimentação', 'Zoozzy'),
(928, 'Manutenção Elétrica', 'Vinder'),
(929, 'Manutenção Hidráulica', 'Zoovu'),
(930, 'Manutenção Elétrica', 'Meevee'),
(931, 'Segurança', 'Topicstorm'),
(932, 'Manutenção Elétrica', 'Twimbo'),
(933, 'Limpeza', 'Bubbletube'),
(934, 'Limpeza', 'Dynabox'),
(935, 'Manutenção Hidráulica', 'Edgetag'),
(936, 'Alimentação', 'Oyope'),
(937, 'Manutenção Elétrica', 'Dabjam'),
(938, 'Segurança', 'Gigabox'),
(939, 'Manutenção Elétrica', 'Jetwire'),
(940, 'Manutenção Hidráulica', 'Quatz'),
(941, 'Manutenção Elétrica', 'Meeveo'),
(942, 'Manutenção Hidráulica', 'Thoughtmix'),
(943, 'Alimentação', 'Thoughtbridge'),
(944, 'Segurança', 'Twinte'),
(945, 'Manutenção Elétrica', 'Camimbo'),
(946, 'Manutenção Hidráulica', 'Yakitri'),
(947, 'Alimentação', 'Izio'),
(948, 'Manutenção Hidráulica', 'Thoughtmix'),
(949, 'Manutenção Geral', 'Skiptube'),
(950, 'Manutenção Geral', 'Yacero'),
(951, 'Segurança', 'Fatz'),
(952, 'Segurança', 'Skiptube'),
(953, 'Manutenção Hidráulica', 'Jatri'),
(954, 'Manutenção Elétrica', 'Zooxo'),
(955, 'Alimentação', 'Photobug'),
(956, 'Segurança', 'Thoughtstorm'),
(957, 'Alimentação', 'Edgepulse'),
(958, 'Manutenção Elétrica', 'Browsecat'),
(959, 'Segurança', 'Livetube'),
(960, 'Alimentação', 'Devshare'),
(961, 'Segurança', 'Wordtune'),
(962, 'Manutenção Elétrica', 'Babbleopia'),
(963, 'Limpeza', 'Mynte'),
(964, 'Manutenção Hidráulica', 'Skajo'),
(965, 'Limpeza', 'Mudo'),
(966, 'Manutenção Hidráulica', 'Talane'),
(967, 'Manutenção Elétrica', 'Thoughtbeat'),
(968, 'Segurança', 'Zoonder'),
(969, 'Manutenção Geral', 'Twinder'),
(970, 'Manutenção Hidráulica', 'Demizz'),
(971, 'Segurança', 'Zoonder'),
(972, 'Limpeza', 'Skalith'),
(973, 'Alimentação', 'Photojam'),
(974, 'Segurança', 'Reallinks'),
(975, 'Manutenção Hidráulica', 'Zooveo'),
(976, 'Limpeza', 'Jaloo'),
(977, 'Alimentação', 'Skyble'),
(978, 'Manutenção Elétrica', 'Jaxnation'),
(979, 'Limpeza', 'Voolia'),
(980, 'Manutenção Geral', 'Voomm'),
(981, 'Alimentação', 'Zoonoodle'),
(982, 'Alimentação', 'Zoombeat'),
(983, 'Manutenção Hidráulica', 'Talane'),
(984, 'Manutenção Hidráulica', 'Shuffletag'),
(985, 'Segurança', 'Devpulse'),
(986, 'Manutenção Hidráulica', 'Photolist'),
(987, 'Segurança', 'Devpulse'),
(988, 'Manutenção Elétrica', 'Dabvine'),
(989, 'Manutenção Elétrica', 'Devshare'),
(990, 'Alimentação', 'Edgetag'),
(991, 'Alimentação', 'Yamia'),
(992, 'Manutenção Elétrica', 'Myworks'),
(993, 'Limpeza', 'Vimbo'),
(994, 'Limpeza', 'Centidel'),
(995, 'Alimentação', 'Kayveo'),
(996, 'Segurança', 'Trudeo'),
(997, 'Segurança', 'Janyx'),
(998, 'Alimentação', 'Camimbo'),
(999, 'Limpeza', 'Meetz'),
(1000, 'Manutenção Geral', 'Wordpedia');
